module.exports = PUSH_NOTIFICATIONS_TYPES = {
    SEND_TO_ALL_DELIVERY_USERS: 'SEND_TO_ALL_DELIVERY_USERS', 
    SEND_ONLY_TO_USERS_LIST: 'SEND_ONLY_TO_USERS_LIST', 
    SEND_TO_ALL: 'SEND_TO_ALL'
}
