module.exports = USER_ROLES = {
    STORE_OWNER: 'STORE_OWNER', 
    CLIENT_USER: 'CLIENT_USER', 
    CONSUMER_USER: 'CONSUMER_USER', 
    DELIVERY_USER: 'DELIVERY_USER', 
    ADMIN: 'ADMIN'
}
